### ISSUE TITLE
Move docs to Docusaurus 

### ISSUE THREAD

**Issue by timgl** [PostHog/docs#9]
This looks like exactly what we need:
https://v2.docusaurus.io/docs/introduction
- SEO friendly
- Search
- Document versioning
- Looks good
- Configurable sidebar
- It even [deploys to github pages](https://v2.docusaurus.io/docs/deployment#deploying-to-github-pages)

cc @mariusandra

**Comment by jamesefhawkins** [comment]
I'd rather get the docs and the website onto the same platform in order that our stack is simpler and so it's more consistent between the two, as it'd be nice to have the handbook on it as well, and for that to make up some of the internal pages on the site, similar to how GitLab do things.

I think Gatsby or NextJS look like easy ways of achieving all of the above (they also produce very similar layouts).

Gatsby looks a little simpler and is more extensible. Next JS is a bit more popular but isn't really used for docs as much, so I'd pick Gatsby.

**Comment by mariusandra** [comment]
Perhaps docusaurus could even be that platform? With v2 they have moved from being a simple "md" -> "html/jsx" pipeline to a true alternative to gatsby and others.

With almost no effort, I was able to generate this site with docusaurus:

https://kea-docs.netlify.app/docs/introduction/quickstart

All the documentation pages are just Markdown -> HTML. Plus it came with a nice blog engine out of the box. The homepage however is pure JSX/React... and I could add any number of other custom pages.

I don't know how well gatsby/next do the markdown -> page conversion, which is absolutely essential to be able to easily update the meat of the docs.

Also, advice I've read is to keep your "app.company.com" separate from "www.company.com", as eventually they will be handled by different teams. The same principle also applies for technical documentation IMO.

**Comment by jamesefhawkins** [comment]
# Gatsby versus Docusaurus

I think Gatsby is better established - it also has good support for MD -> HTML and has tons of plugins too. It's basically a framework that would allow us to build a powerful regular website over time. Docusaurus has a better default setup for docs, but it's also trivial to get Gatsby to produce something identical looking.

# Domain setup

app.company.com seems sensible.

However, having docs.company.com separate to company.com is [less desirable](https://moz.com/community/q/the-great-subdomain-vs-subfolder-debate-what-is-the-best-answer) from an SEO perspective; you have to build domain authority up across multiple domains to get the same rankings and organic traffic, so I'd rather end up with company.com/docs and company.com/handbook.

I think that will drive greater consistency, which is a key quality signal - I'd rather not have designs / fonts etc in two different places.

**Comment by SanketDG** [comment]
> I think Gatsby is better established - it also has good support for MD -> HTML and has tons of plugins too. It's basically a framework that would allow us to build a powerful regular website over time. Docusaurus has a better default setup for docs, but it's also trivial to get Gatsby to produce something identical looking.

I am not sure I can agree. There definitely seems to be a steep learning curve with Gatsby because of all the integrations of fetching dynamic data and then building a "static" set of pages.

If PostHog doesn't need to fetch any form of dynamic data, and just landing + docs, Docusaurus seems to be a better fit. I could take this up whether Gatsby or Docusaurus is decided.

**Comment by jamesefhawkins** [comment]
Closed as we set up posthog.com and our docs all from Gatsby -  @SanketDG, it was a little harder to get going with, but since our use case is pretty vanilla, it wasn't too bad :)
